#%RAML 1.0
title: uca-elm-api
description: This api is meant for the retrieval of information for saudi nationals, expatries and companies
version: v1
baseUri: http://{environment}:8081/uca-elm-api/{version}
baseUriParameters:
  environment:
    description: dev, test, dr, prod
    enum : [dev-mule-01,test-mule-01,dr-mule-01,prod-mule-01]

protocols:
  - HTTP
  - HTTPS
mediaType: 
  - application/json
  

uses:
  ucaTypes: library/schemaTypes.raml
  
traits:
  transaction-header : !include exchange_modules/2b034c13-b738-4dde-96a1-045fa5ebd1dc/uca-header-transactionraml/1.0.0/uca-header-transaction-id.raml

/alienStatus:
  post:
    description: The alienStatus function allows the user to Verify the validity of sent Iqama Number, to be according to NIC standards, verify the existence of the sent Iqama Number, to have a registered record at NIC and return AlienStatus.
    is: [transaction-header]
    body:
      application/json:
        type: ucaTypes.alienStatusRequestType
        example: !include examples/alienStatusRequestExample.json
          
    responses:
      200:
        body:
          application/json:
            type: ucaTypes.alienStatusResponseType
            example: !include examples/alienStatusResponseExample.json
      400:
        description: Bad request
        body:
          application/json:
            example: !include examples/400-errorCodeExample.json
      500:
        description: Internal Server Error
        body:
          application/json:
            example: !include examples/500-errorCodeExample.json
            
/alienInfoByIqama:
  post:
    description: The alienInfoByIqama function allows the user to Verify the validity of sent Iqama Number, to be according to NIC standards, verify the existence of the sent Iqama Number, to have a registered record at NIC and return AlienInfoByIqama.
    is: [transaction-header]
    body:
      application/json:
        type: ucaTypes.alienInfoByIqamaRequestType
        example: !include examples/alienInfoByIqamaRequestExample.json
    responses:
      200:
        body:
          application/json:
            type: ucaTypes.alienInfoByIqamaResponseType
            example: !include examples/alienInfoByIqamaResponseExample.json
      400:
        description: Bad request
        body:
          application/json:
            example: !include examples/400-errorCodeExample.json
      500:
        description: Internal Server Error
        body:
          application/json:
            example: !include examples/500-errorCodeExample.json
        
/alienInfoByBorderNumber:
  description: The alienInfoByBorderNumber function allows the user to Verify the validity of sent Iqama Number, to be according to NIC standards, verify the existence of the sent Iqama Number, to have a registered record at NIC and return alienInfoByBorderNumber.
  is: [transaction-header]
  post:
    body:
      application/json:
        type: ucaTypes.alienInfoByBorderNumberRequestType
        example: !include examples/alienInfoByBorderNumberRequestExample.json
    responses:
      200:
        body:
          application/json:
            type: ucaTypes.alienInfoByBorderNumberResponseType
            example: !include examples/alienInfoByBorderNumberResponseExample.json
      400:
        description: Bad request
        body:
          application/json:
            example: !include examples/400-errorCodeExample.json
      500:
        description: Internal Server Error
        body:
          application/json:
            example: !include examples/500-errorCodeExample.json

/alienInfoByIqamaAndDependent:
  post:
    description: The alienInfoByIqamaAndDependent function allows the user to Verify the validity of sent Iqama Number, to be according to NIC standards, verify the existence of the sent Iqama Number, to have a registered record at NIC and return alienInfoByIqamaAndDependent.
    is: [transaction-header]
    body:
      application/json:
        type: ucaTypes.alienInfoByIqamaAndDependentRequestType
        example: !include examples/alienInfoByIqamaAndDependentRequestExample.json
        
    responses:
      200:
        body:
          application/json:
            type: ucaTypes.alienInfoByIqamaAndDependentResponseType
            example: !include examples/alienInfoByIqamaAndDependentResponseExample.json
      400:
        description: Bad request
        body:
          application/json:
            example: !include examples/400-errorCodeExample.json
      500:
        description: Internal Server Error
        body:
          application/json:
            example: !include examples/500-errorCodeExample.json
            

/citizenInfo:
  post:
    description: The citizenInfo function allows the user to Verify the validity of sent NIN, to be according to NIC standards, verify the existence of the sent NIN, to have a registered record at NIC and return citizenInfo.
    is: [transaction-header]
    body:
      application/json:
        type: ucaTypes.citizenInfoRequestType
        example: !include examples/citizenInfoRequestExample.json
    responses:
      200:
        body:
          application/json:
            type: ucaTypes.citizenInfoResponseType
            example: !include examples/citizenInfoResponseExample.json
      400:
        description: Bad request
        body:
          application/json:
            example: !include examples/400-errorCodeExample.json
      500:
        description: Internal Server Error
        body:
          application/json:
            example: !include examples/500-errorCodeExample.json


/alienInfoByIqamaAndDateOfBirth:
  post:
    description: The alienInfoByIqamaAndDateOfBirth function allows the user to Verify the validity of sent Iqama Number, to be according to NIC standards, verify the existence of the sent Iqama Number, to have a registered record at NIC and return alienInfoByIqamaAndDateOfBirth.
    is: [transaction-header]
    body:
      application/json:
        type: ucaTypes.alienInfoByIqamaAndDateOfBirthRequestType
        example: !include examples/alienInfoByIqamaAndDateOfBirthRequestExample.json
    responses:
      200:
        body:
          application/json:
            type: ucaTypes.alienInfoByIqamaAndDateOfBirthResponseType
            example: !include examples/alienInfoByIqamaAndDateOfBirthResponseExample.json
      400:
        description: Bad request
        body:
          application/json:
            example: !include examples/400-errorCodeExample.json
      500:
        description: Internal Server Error
        body:
          application/json:
            example: !include examples/500-errorCodeExample.json


/companyInfoBySponseredIqama:
  post:
    description: The companyInfoBySponseredIqama function allows the user to Verify the validity of sent Company Number, to be according to NIC standards, verify the existence of the sent Company Number, to have a registered record at NIC and return companyInfoBySponseredIqama.
    is: [transaction-header]
    body:
      application/json:
        type: ucaTypes.companyInfoBySponseredIqamaRequestType
        example: !include examples/companyInfoBySponseredIqamaRequestExample.json
    responses: 
      200:
       body:
         application/json:
           type: ucaTypes.companyInfoBySponseredIqamaResponseType
           example: !include examples/companyInfoBySponseredIqamaResponseExample.json
      400:
        description: Bad request
        body:
          application/json:
            example: !include examples/400-errorCodeExample.json
      500:
        description: Internal Server Error
        body:
          application/json:
            example: !include examples/500-errorCodeExample.json

/citizenDepInfo:
  post:
    description: The citizenDepInfo function allows the user to Verify the validity of sent NIN, to be according to NIC standards, verify the existence of the sent NIN, to have a registered record at NIC and return citizenDepInfo.
    is: [transaction-header]
    body:
      application/json:
        type: ucaTypes.citizenDepInfoRequestType
        example: !include examples/citizenDepInfoRequestExample.json
    responses:
      200:
        body:
          application/json:
            type: ucaTypes.citizenDepInfoResponseType
            example: !include examples/citizenDepInfoResponseExample.json
      400:
        description: Bad request
        body:
          application/json:
            example: !include examples/400-errorCodeExample.json
      500:
        description: Internal Server Error
        body:
          application/json:
            example: !include examples/500-errorCodeExample.json

/alienAddressInfo:
  post:
    description: The alienAddressInfo function allows the user to Verify the validity of sent Iqama Number, to be according to NIC standards, verify the existence of the sent Iqama Number, to have a registered record at NIC and return alienAddressInfo.
    is: [transaction-header]
    body:
      application/json:
        type: ucaTypes.alienAddressInfoRequestType
        example: !include examples/alienAddressInfoRequestExample.json
    responses:
      200:
        body:
          application/json:
            type: ucaTypes.alienAddressInfoResponseType
            example: !include examples/alienAddressInfoResponseExample.json
      400:
        description: Bad request
        body:
          application/json:
            example: !include examples/400-errorCodeExample.json
      500:
        description: Internal Server Error
        body:
          application/json:
            example: !include examples/500-errorCodeExample.json

/citizenAddressInfo:
  post:
    description: The citizenAddressInfo function allows the user to Verify the validity of sent NIN, to be according to NIC standards, verify the existence of the sent NIN, to have a registered record at NIC and return citizenAddressInfo.
    is: [transaction-header]
    body:
      application/json:
        type: ucaTypes.citizenAddressInfoRequestType
        example: !include examples/citizenAddressInfoRequestExample.json
    responses:
      200:
        body:
          application/json:
            type: ucaTypes.citizenAddressInfoResponseType
            example: !include examples/citizenAddressInfoResponseExample.json
      400:
        description: Bad request
        body:
          application/json:
            example: !include examples/400-errorCodeExample.json
      500:
        description: Internal Server Error
        body:
          application/json:
            example: !include examples/500-errorCodeExample.json

/companyAddressInfoByCr:
  post:
    description: The companyAddressInfoByCr function allows the user to Verify the validity of sent Company Number, to be according to NIC standards, verify the existence of the sent Company Number, to have a registered record at NIC and return companyAddressInfoByCr.
    is: [transaction-header]
    body:
      application/json:
        type: ucaTypes.companyAddressInfoByCrRequestType
        example: !include examples/companyAddressInfoByCrRequestExample.json
    responses:
      200:
        body:
          application/json:
            type: ucaTypes.companyAddressInfoByCrResponseType
            example: !include examples/companyAddressInfoByCrResponseExample.json
      400:
        description: Bad request
        body:
          application/json:
            example: !include examples/400-errorCodeExample.json
      500:
        description: Internal Server Error
        body:
          application/json:
            example: !include examples/500-errorCodeExample.json
      
            


            





        